In [17]:
import numpy as np
arr = np.arange(5)
lst = [15,9,5,4,5]
arr_lst = np.array(lst)
a = np.subtract(arr, arr_lst)
a

array([-15,  -8,  -3,  -1,  -1])

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b=np.array([[4,5],[1,1]])
a=np.array([[1,2],[2,3]])
np.multiply(a,b)

array([[ 4, 10],
       [ 2,  3]])

In [29]:
a=[11, 43, 66, 77, 333, 88, 666]


np.mean(a)


183.42857142857142

In [30]:
np.median(a)

77.0