# Basics of Numpy

In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#shape 
a.shape

(2, 3)

In [7]:
#type
type(a)

numpy.ndarray

In [10]:
#reshape
a.shape=(3,2)


In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# resize array
a = np.array([[1,2,3],[4,5,6]])
b = np.resize(a,(4,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
#auto arrangement
x = np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

In [22]:
import numpy as np
x = [1,2,3,4,5,6]
b = np.resize(a,(2,3))
print (b)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
import numpy as np
x = [1,2,3,4,5,6]
b = a.reshape(2,3)
print (b)

[[1 2 3]
 [4 5 6]]
